# Guide to Explore this NumPy Notes in Google Colab

Welcome to the **NumPy** guide on by Aviral! This guide will help you efficiently explore and understand the code in your notebook.

---

## Steps to Explore the Notebook:

### 1. **Run All Code Cells**
- **Run all code cells at once** by going to the **Runtime** menu at the top of Google Colab.
- Select **Run all** to execute the entire notebook.
- Wait for the output of each cell to display before proceeding, as the computations will be performed sequentially.

### 2. **Track Arrays and Shapes**
- As the code runs, **keep track of the arrays** being created and printed. The shapes of the arrays are important to understand how they are structured.
  
**Example Arrays**:
- `np1`, `np2`, `np3`, `np4`, etc., are all arrays with different shapes and values.
- **Shape of an Array**: You can check the shape of any array by using `array.shape`.

### 3. **Key Concepts to Understand**
Focus on the following key concepts as you go through the notebook:

- **Array Creation**: Understand how different types of arrays are created, such as:
  - `np.array()`: Create an array from a list.
  - `np.zeros()`: Create an array filled with zeros.
  - `np.full()`: Create an array filled with a constant value.
  - `np.arange()`: Create an array with a range of values.
  
- **Reshaping**: Learn how to reshape arrays to change their structure:
  - **Example**: `np1.reshape(3, 4)` reshapes a 1D array into a 2D array with 3 rows and 4 columns.
  
- **Mathematical Functions**: Observe how you can perform mathematical operations on arrays:
  - `np.sqrt()`, `np.exp()`, `np.log()`, `np.sin()`, etc., apply mathematical functions element-wise to arrays.
  
- **Sorting**: Understand how to sort arrays using `np.sort()` and see how the order of elements changes.
  
### 4. **Observe the Output**
- After running each code cell, observe how the output changes:
  - For example, after running `np1 = np.array([-2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])`, you will see the array printed.
  - When performing operations like `np.sqrt(np1)`, notice how negative values are handled, or when performing `np.sort(npRandom)`, see how the array is rearranged.

### 5. **Iteration and `np.where()`**
- Pay attention to how iteration works in arrays:
  - For 1D arrays, iteration is straightforward using a simple `for` loop.
  - For multi-dimensional arrays, you can iterate over rows, columns, or deeper using nested loops or `np.nditer()`.
  
- **`np.where()`**: This function is useful for filtering arrays based on a condition.
  - For example: `np.where(npRandom == 4)` returns the indices of the array where the value is 4.
  - You can use `np.where()` to extract specific elements, like even numbers or prime numbers from an array.

### 6. **Summary of Arrays and Shapes**
- **1D Arrays**: `np1`, `np2`, `np3` (shapes like `(12,)`, `(10,)`, `(5,)`)
- **2D Arrays**: `np2d`, reshaped arrays (shapes like `(2, 5)`, `(3, 4)`)
- **3D Arrays**: `np3d` (shape like `(2, 2, 3)`)
- **4D Arrays**: `np4d` (shape like `(1, 1, 1, 1, 1, 1, 1, 1, 10, 10)`)

---

By following these steps, you will gain a deep understanding of how NumPy arrays work, and how to efficiently manipulate them for your data science or machine learning tasks.







In [1]:
# Numpy = Numeric Python
# Datatype = ndarray = n-dim array


In [2]:
import numpy as np

In [3]:
np1 = np.array([-2,-1,0,1,2,3,4,5,6,7,8,9])
print(np1)

[-2 -1  0  1  2  3  4  5  6  7  8  9]


In [4]:
np1.shape #tells lenght

(12,)

In [5]:
#Range
np2 = np.arange(10) #np.arrange(last+1) "default start = 0, step = 1"
print(np2)

[0 1 2 3 4 5 6 7 8 9]


In [62]:
#Step
np3 = np.arange(10,20,2) #np.arrange(first, last+1, step)
print(np3)

[10 12 14 16 18]


In [7]:
np4 = np.zeros(10) #np.zeros(lenght)
print(np4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
#multiDimensional zeros
np5 = np.zeros((2,4)) #np.zeros((row,column)) "row= number of element in coloumn and vice versa"
print(np5)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [63]:
#Full
np6 = np.full((2,3),5) #np.full((shape ,value)
print(np6)

[[5 5 5]
 [5 5 5]]


In [10]:
#multidiemnsional Full
np7 = np.full((2,3),5) #np.full((row,column),value)
print(np7)

[[5 5 5]
 [5 5 5]]


In [11]:
#convert python list to numpy
list1 = [1,2,3,4,5]
np8 = np.array(list1)
print(np8)

[1 2 3 4 5]


In [12]:
#slicing
print(np1)
print("slice from index 1 to 5:",np1[1:6])

[-2 -1  0  1  2  3  4  5  6  7  8  9]
slice from index 1 to 5: [-1  0  1  2  3]


In [64]:
#return something till the end of the array
print(np1[5:]) #from index 5 to end

[3 4 5 6 7 8 9]


In [14]:
#slicing with steps
print(np1[1:6:2]) # first, last+step, step

[-1  1  3]


In [15]:
#steps on the entire array
print(np1[::2])

[-2  0  2  4  6  8]


In [16]:
#2d array
np2d = np.array([[1,2,3,4,5],[6,7,8,9,10]]) #initially it was np9, so next you will see np10, np9 is not missing but just renamed... continue ;-)
#pull out single item
print(np2d[1,2]) #counting start from 0, so rows are 0 and 1, colmn are 0,1,2,3,4

8


In [17]:
 # slice a 2d array
print(np2d[0:1,1:4]) #[rowStart:rowEnd+1,colmnStart:colmnEnd+1]

[[2 3 4]]


In [18]:
#slice from both rows
print(np2d[0:2,1:3])


[[2 3]
 [7 8]]


In [19]:
#square root of each element
print(np1)
print(np.sqrt(np1))

[-2 -1  0  1  2  3  4  5  6  7  8  9]
[       nan        nan 0.         1.         1.41421356 1.73205081
 2.         2.23606798 2.44948974 2.64575131 2.82842712 3.        ]


C:\Users\Acer\AppData\Local\Temp\ipykernel_19224\429418698.py:3: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(np1))


In [66]:
#absolute value
print(np.absolute(np1))

[2 1 0 1 2 3 4 5 6 7 8 9]


In [21]:
#exponents
print(np.exp(np1))

[1.35335283e-01 3.67879441e-01 1.00000000e+00 2.71828183e+00
 7.38905610e+00 2.00855369e+01 5.45981500e+01 1.48413159e+02
 4.03428793e+02 1.09663316e+03 2.98095799e+03 8.10308393e+03]


In [22]:
#min/max
print(np.min(np1))
print(np.max(np1))

-2
9


In [23]:
#sign positive or negative
print(np.sign(np1))

[-1 -1  0  1  1  1  1  1  1  1  1  1]


In [24]:
#trigonometry
print(np.sin(np1))
print(np.cos(np1))
print(np.tan(np1))

[-0.90929743 -0.84147098  0.          0.84147098  0.90929743  0.14112001
 -0.7568025  -0.95892427 -0.2794155   0.6569866   0.98935825  0.41211849]
[-0.41614684  0.54030231  1.          0.54030231 -0.41614684 -0.9899925
 -0.65364362  0.28366219  0.96017029  0.75390225 -0.14550003 -0.91113026]
[ 2.18503986 -1.55740772  0.          1.55740772 -2.18503986 -0.14254654
  1.15782128 -3.38051501 -0.29100619  0.87144798 -6.79971146 -0.45231566]


In [25]:
#logarithm
print(np.log(np1))


[       nan        nan       -inf 0.         0.69314718 1.09861229
 1.38629436 1.60943791 1.79175947 1.94591015 2.07944154 2.19722458]


C:\Users\Acer\AppData\Local\Temp\ipykernel_19224\2804834865.py:2: RuntimeWarning: divide by zero encountered in log
  print(np.log(np1))
C:\Users\Acer\AppData\Local\Temp\ipykernel_19224\2804834865.py:2: RuntimeWarning: invalid value encountered in log
  print(np.log(np1))


For more Universal Functions;

[Click Here](https://docs.scipy.org/doc/numpy-1.10.1/reference/ufuncs.html)

In [70]:
#copy vs view
np10 = np.array([1,2,3,4,5,6,7,8,9,10])
np10copy = np10.copy()
np10view = np10.view()
print("real:", np10, "\ncopy:", np10copy, "\nview:", np10view)

real: [ 1  2  3  4  5  6  7  8  9 10] 
copy: [ 1  2  3  4  5  6  7  8  9 10] 
view: [ 1  2  3  4  5  6  7  8  9 10]


In [71]:
np10[0] = 0
print("real:", np10, "\ncopy:", np10copy, "\nview:", np10view)

real: [ 0  2  3  4  5  6  7  8  9 10] 
copy: [ 1  2  3  4  5  6  7  8  9 10] 
view: [ 0  2  3  4  5  6  7  8  9 10]


In [72]:
np10copy[1] = 0
print("real:", np10, "\ncopy:", np10copy, "\nview:", np10view)

real: [ 0  2  3  4  5  6  7  8  9 10] 
copy: [ 1  0  3  4  5  6  7  8  9 10] 
view: [ 0  2  3  4  5  6  7  8  9 10]


In [29]:
np10view[0] = 33
print("real:", np10, "\ncopy:", np10copy, "\nview:", np10view)

real: [33  2  3  4  5  6  7  8  9 10] 
copy: [ 1  0  3  4  5  6  7  8  9 10] 
view: [33  2  3  4  5  6  7  8  9 10]


In [73]:
#3d array (row, row, colmn)
np3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
#4d array (row, row, row, colmn)
np4d= np.array([[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]],[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]])

In [31]:
#shapes of array
print("1d:", np1 ,"shape:",np1.shape)
print("2d:", np2d ,"shape:",np2d.shape)
print("3d:", np3d ,"shape:",np3d.shape)
print("4d:", np4d ,"shape:",np4d.shape)

1d: [-2 -1  0  1  2  3  4  5  6  7  8  9] shape: (12,)
2d: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]] shape: (2, 5)
3d: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] shape: (2, 2, 3)
4d: [[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]


 [[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]] shape: (2, 2, 2, 3)


In [75]:
#reshaping
np1dto2d = np1.reshape(2,5) #will throw error
print(np1dto2d)

ValueError: cannot reshape array of size 12 into shape (2,5)

In [33]:
#1d to 2d
print("12:\n",np1)
np1dto2d = np1.reshape(3,4)
print("3x4:\n",np1dto2d)
np1dto2d = np1.reshape(6,2)
print("6x2:\n",np1dto2d)
#3x4 = 6x2 = 12

12:
 [-2 -1  0  1  2  3  4  5  6  7  8  9]
3x4:
 [[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]
6x2:
 [[-2 -1]
 [ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]]


In [34]:
#1d to 3d
np1dto3d = np1.reshape(2,2,3)
print(np1dto3d)
#2x2x3=12

[[[-2 -1  0]
  [ 1  2  3]]

 [[ 4  5  6]
  [ 7  8  9]]]


In [35]:
#flatten to 3d to 1d
np3dto1d = np3d.reshape(-1)
print(np3dto1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [36]:
#3d to 2d
np3dto2d = np3d.reshape(2,2*3) # or (2,6)
print(np3dto2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [37]:
#iterating through 1d array
for x in np1:
    print(x)

-2
-1
0
1
2
3
4
5
6
7
8
9


In [38]:
#iterating through 2d array
for x in np2d:
    print(x) #x = rows

[1 2 3 4 5]
[ 6  7  8  9 10]


In [39]:
#iterating through 2d array deeper
for x in np2d:
    for y in x:
        print(y)

1
2
3
4
5
6
7
8
9
10


In [40]:
#iterating through 3d array
for x in np3d:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [41]:
#iterating through 3d array deeper
for x in np3d:
    for y in x:
        print(y)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [42]:
#iterating through 3d array more deeper
for x in np3d:
    for y in x:
        for z in y:
            print(z) #getting complex??

1
2
3
4
5
6
7
8
9
10
11
12


In [43]:
#easier way
for x in np.nditer(np3d):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [44]:
#making a 10-d array for fun and using nditer!
np10d = np.arange(100).reshape((1, 1, 1, 1, 1, 1, 1, 1, 10, 10))

print("Shape:", np10d.shape)
# Using nditer to iterate through each element in the 10D array
for x in np.nditer(np10d):
    print(x)


Shape: (1, 1, 1, 1, 1, 1, 1, 1, 10, 10)
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [45]:
# sorting in numpy
npRandom = np.array([2,4,2,7,3,4,6,8,9,4,2,4,5,6,7,89,3,22,34,5,56,5,44]) #numerical
npRandom_Sorted = np.sort(npRandom)
print("random:",npRandom)
print("sorted:",npRandom_Sorted)

random: [ 2  4  2  7  3  4  6  8  9  4  2  4  5  6  7 89  3 22 34  5 56  5 44]
sorted: [ 2  2  2  3  3  4  4  4  4  5  5  5  6  6  7  7  8  9 22 34 44 56 89]


In [76]:
npNames = np.array(["Zoya","Rahul", "Abhay","Vaibhav","Seema", "Ansh"]) #string
print("random:",npNames)
print("sorted:",np.sort(npNames))


random: ['Zoya' 'Rahul' 'Abhay' 'Vaibhav' 'Seema' 'Ansh']
sorted: ['Abhay' 'Ansh' 'Rahul' 'Seema' 'Vaibhav' 'Zoya']


In [47]:
#sorting true false
npBool = np.array([True, False, True, False, True])
print("random:",npBool)
print("sorter:",np.sort(npBool))

random: [ True False  True False  True]
sorter: [False False  True  True  True]


In [48]:
#return a copy not change original after sorting
print(np.sort(npNames))
print(npNames)

['Abhay' 'Ansh' 'Rahul' 'Seema' 'Vaibhav' 'Zoya']
['Zoya' 'Rahul' 'Abhay' 'Vaibhav' 'Seema' 'Ansh']


In [49]:
#sorting 2d array
np2d_random = np.array([[2,4,2,7,3],[4,6,8,9,4],[2,4,2,7,3], [4,6,8,9,4],[2,4,2,7,3]])
print("random:\n",np2d_random)
print("sorted:\n",np.sort(np2d_random))

random:
 [[2 4 2 7 3]
 [4 6 8 9 4]
 [2 4 2 7 3]
 [4 6 8 9 4]
 [2 4 2 7 3]]
sorted:
 [[2 2 3 4 7]
 [4 4 6 8 9]
 [2 2 3 4 7]
 [4 4 6 8 9]
 [2 2 3 4 7]]


In [50]:
#finding index number of an element of array
print(np1)
x = np.where(np1 == 3) #return tuple of index
print(x)

[-2 -1  0  1  2  3  4  5  6  7  8  9]
(array([5]),)


In [51]:
#get only index number than tuple
print(x[0])

[5]


In [52]:
#what if we print xth element of np1?
print(np1[x])

[3]


In [53]:
#if more than 1 same element exists in a array
print(np.where(npRandom == 4)[0])

[ 1  5  9 11]


In [54]:
# Finds and prints all occurrences of the value 4 in the npRandom array
print(npRandom[np.where(npRandom == 4)])

[4 4 4 4]


In [55]:
#return only even numbers
print(npRandom[np.where(npRandom % 2 == 0)])

[ 2  4  2  4  6  8  4  2  4  6 22 34 56 44]


In [56]:
#return only odd numbers using where function!
print(npRandom[np.where(npRandom % 2 != 0)]) #remember where fn returns only index numbers, but we can get corresponding elements.


[ 7  3  9  5  7 89  3  5  5]


In [57]:
#filtering Numpy Arrays with Boolean Index Lists.
np11 = np.array([0,9,8,7,6,5,4,3,2,1])
print(np11)
x = [True, False, True, False, True, False, True, False, True, False] # Defines a list x of boolean values; these will act as a mask for selecting elements from np11 (Keep True, remove False)
print(np11[x])

[0 9 8 7 6 5 4 3 2 1]
[0 8 6 4 2]


In [78]:
# Writing an loop to make a boolean index list to filter out every other number than prime number
x = []
for i in npRandom:
  for j in range(2, i):
    if i % j == 0:
      x.append(False)
      break
  else:
    x.append(True)
print(x)

[True, False, True, True, True, False, False, False, False, False, True, False, True, False, True, True, True, False, False, True, False, True, False]


In [59]:
print(npRandom[x])

[ 2  2  7  3  2  5  7 89  3  5  5]


In [60]:
#shortcut
x = npRandom % 2 == 0
print(x)
print(npRandom[x])

[ True  True  True False False  True  True  True False  True  True  True
 False  True False False False  True  True False  True False  True]
[ 2  4  2  4  6  8  4  2  4  6 22 34 56 44]


# **Happy learning!**
[*Click here for more content from me!*](https://aviral.code.blog)