In [1]:
import numpy as np

In [2]:
my_lst = ([1,2,3,4,5,6])

In [3]:
arr = np.array(my_lst)

In [13]:
arr

array([[1, 2, 3, 4, 5, 6]])

In [11]:
type(arr)

numpy.ndarray

In [12]:
arr.shape #1 represent dimension of list and 6 represent number of elements in each array

(1, 6)

In [14]:
xyz =np.array([[[1,2,3],[4,5,6]],[[7,8,9],[4,3,8]]])
xyz

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [4, 3, 8]]])

In [16]:
xyz.shape

(2, 2, 3)

In [18]:
ar.reshape(5,3)

NameError: name 'ar' is not defined

In [19]:
##multinested array
lst

NameError: name 'lst' is not defined

In [31]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr1.shape

(3, 3)

In [34]:
ar =[1,2,3,4,5]
ar =[-1]

In [35]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
arr1[0:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [38]:
arr2=np.array([[1,2,3,4,5],[4,5,6,2,8],[7,8,9,2,1]])
arr2

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 2, 8],
       [7, 8, 9, 2, 1]])

In [30]:
arr2[1:,:]

array([[4, 5, 6, 2, 8],
       [7, 8, 9, 2, 1]])

In [56]:
arr2.reshape(1,3)

ValueError: cannot reshape array of size 15 into shape (1,3)

In [41]:
arr

array([[1, 2, 3, 4, 5, 6]])

In [42]:
arr[3:] = 100
arr

array([[1, 2, 3, 4, 5, 6]])

In [44]:
arr3=np.array([1,2,3,4,5,6])
arr3

array([1, 2, 3, 4, 5, 6])

In [49]:
arr3[3:]= 100
arr3

array([  1,   2,   3, 100, 100, 100])

In [52]:
x1 = np.arange(0,10).reshape(2,5) # arange takes random value from given range
x1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [53]:
x2 = np.arange(0,10).reshape(2,5)
x2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [54]:
x1 + x2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [55]:
x1*x2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])